### ISSUE TITLE
Typo in key binding

### ISSUE THREAD

**Issue by Bananeweizen** [DieterMai/ProjectSelect#1]
![grafik](https://user-images.githubusercontent.com/406876/94293386-78fbd480-ff5e-11ea-8c69-314e920a9d03.png)

**Comment by DieterMai** [comment]
I'm just happy, that someone looks at my stuff

**Comment by DieterMai** [comment]
I submitted a fix and a new version is available. Thank you for the hint.

**Comment by Bananeweizen** [comment]
I must admit, without the current tweet of Lars I wouldn't even have known the plugin. Now I've put it into my teams Oomph setup to make it available for everyone. Good work, thanks.

**Comment by DieterMai** [comment]
I'm happy to hear that.
